name: Schedule Pull Request Merge
on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize
jobs:
    schedule_pull_request_merge:
        runs-on: ubuntu-latest
        steps:
            - uses: AlbertSanIza/schedule-pull-request-merge-action@v1.0.9
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
